// src/routes/contato/+page.svelte
<script lang="ts">
	import { Mail, Phone } from 'lucide-svelte';
	import SEO from '$lib/components/seo.svelte';

	const whatsappLink = `https://wa.me/5562982653996?text=${encodeURIComponent('Olá, Jaqueline! Gostaria de marcar uma conversa.')}`;
	// TODO: Implement authentication check later
	const isAuthenticated = false;

	// WhatsApp Icon component
	const WhatsAppIcon = {
		svg: {
			viewBox: '0 0 448 512',
			path: 'M380.9 97.1C339 55.1 283.2 32 223.9 32c-122.4 0-222 99.6-222 222 0 39.1 10.2 77.3 29.6 111L0 480l117.7-30.9c32.4 17.7 68.9 27 106.1 27h.1c122.3 0 224.1-99.6 224.1-222 0-59.3-25.2-115-67.1-157zm-157 341.6c-33.2 0-65.7-8.9-94-25.7l-6.7-4-69.8 18.3L72 359.2l-4.4-7c-18.5-29.4-28.2-63.3-28.2-98.2 0-101.7 82.8-184.5 184.6-184.5 49.3 0 95.6 19.2 130.4 54.1 34.8 34.9 56.2 81.2 56.1 130.5 0 101.8-84.9 184.6-186.6 184.6zm101.2-138.2c-5.5-2.8-32.8-16.2-37.9-18-5.1-1.9-8.8-2.8-12.5 2.8-3.7 5.6-14.3 18-17.6 21.8-3.2 3.7-6.5 4.2-12 1.4-32.6-16.3-54-29.1-75.5-66-5.7-9.8 5.7-9.1 16.3-30.3 1.8-3.7.9-6.9-.5-9.7-1.4-2.8-12.5-30.1-17.1-41.2-4.5-10.8-9.1-9.3-12.5-9.5-3.2-.2-6.9-.2-10.6-.2-3.7 0-9.7 1.4-14.8 6.9-5.1 5.6-19.4 19-19.4 46.3 0 27.3 19.9 53.7 22.6 57.4 2.8 3.7 39.1 59.7 94.8 83.8 35.2 15.2 49 16.5 66.6 13.9 10.7-1.6 32.8-13.4 37.4-26.4 4.6-13 4.6-24.1 3.2-26.4-1.3-2.5-5-3.9-10.5-6.6z'
		}
	};
</script>

<SEO
	title="Contato - J. Tosta | Agende sua Consulta"
	description="Entre em contato com a psicoterapeuta Jaqueline Tosta. Atendimento em Goiânia, via WhatsApp ou email. Comece sua jornada de transformação hoje."
/>

<div class="container mx-auto px-4 py-12 md:py-20">
	<h1 class="mb-10 text-center text-4xl font-bold text-primary md:text-5xl">Entre em Contato</h1>
	<p class="mb-12 text-center text-lg text-muted-foreground max-w-2xl mx-auto">
		Estou aqui para ouvir você. Escolha a melhor forma de entrar em contato e vamos começar essa
		conversa.
	</p>

	<div class="grid grid-cols-1 gap-8 md:grid-cols-2">
		<!-- WhatsApp Contact Card -->
		<div class="rounded-lg border bg-card text-card-foreground shadow-md">
			<div class="flex flex-col space-y-1.5 p-6">
				<div class="flex items-center gap-2 text-lg font-semibold text-secondary-foreground">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						viewBox={WhatsAppIcon.svg.viewBox}
						class="h-5 w-5"
					>
						<path fill="currentColor" d={WhatsAppIcon.svg.path} />
					</svg>
					WhatsApp
				</div>
				<p class="text-sm text-muted-foreground">
					A forma mais rápida e direta de falar comigo. Clique no botão abaixo para iniciar uma
					conversa.
				</p>
			</div>
			<div class="p-6 pt-0">
				<p class="mb-4 flex items-center text-muted-foreground">
					<Phone class="mr-2 h-4 w-4" /> (62) 98265-3996
				</p>
				<a
					href={whatsappLink}
					class="inline-flex w-full items-center justify-center rounded-md bg-accent px-4 py-2 text-sm font-medium text-accent-foreground transition-colors hover:bg-accent/90"
					target="_blank"
					rel="noopener noreferrer"
				>
					<svg
						xmlns="http://www.w3.org/2000/svg"
						viewBox={WhatsAppIcon.svg.viewBox}
						class="mr-2 h-4 w-4"
					>
						<path fill="currentColor" d={WhatsAppIcon.svg.path} />
					</svg>
					Falar no WhatsApp
				</a>
			</div>
		</div>

		<!-- Email Form Card -->
		<div class="rounded-lg border bg-card text-card-foreground shadow-md">
			<div class="flex flex-col space-y-1.5 p-6">
				<div class="flex items-center gap-2 text-lg font-semibold text-secondary-foreground">
					<Mail class="h-5 w-5" /> Formulário por Email
				</div>
				<p class="text-sm text-muted-foreground">
					Prefere enviar um email? Preencha o formulário abaixo (disponível para usuários logados).
				</p>
			</div>
			<div class="p-6 pt-0">
				{#if isAuthenticated}
					<form class="space-y-4">
						<div>
							<label for="name" class="block text-sm font-medium text-muted-foreground mb-1"
								>Nome</label
							>
							<input
								type="text"
								id="name"
								name="name"
								class="w-full rounded-md border p-2 bg-input"
								placeholder="Seu nome"
								disabled
							/>
						</div>
						<div>
							<label for="email" class="block text-sm font-medium text-muted-foreground mb-1"
								>Email</label
							>
							<input
								type="email"
								id="email"
								name="email"
								class="w-full rounded-md border p-2 bg-input"
								placeholder="seuemail@exemplo.com"
								disabled
							/>
						</div>
						<div>
							<label for="message" class="block text-sm font-medium text-muted-foreground mb-1"
								>Mensagem</label
							>
							<textarea
								id="message"
								name="message"
								rows="4"
								class="w-full rounded-md border p-2 bg-input"
								placeholder="Sua mensagem..."
								disabled
							></textarea>
						</div>
						<button
							type="submit"
							class="w-full inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
							disabled
						>
							Enviar Mensagem (Em Breve)
						</button>
					</form>
				{:else}
					<div
						class="flex flex-col items-center justify-center h-full rounded-md border border-dashed p-8 text-center text-muted-foreground"
					>
						<p class="mb-4">
							O formulário de contato por email está disponível apenas para usuários autenticados.
						</p>
						<!-- TODO: Add Login Button -->
						<p class="mt-4 text-sm">Por favor, utilize o WhatsApp para contato no momento.</p>
					</div>
				{/if}
			</div>
		</div>
	</div>
</div>

// src/app/contato/page.tsx
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Mail, Phone } from "lucide-react";

// Custom SVG for WhatsApp icon (reusing from WhatsAppButton)
const WhatsAppIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 448 512"
    fill="currentColor"
    className="h-5 w-5" // Adjusted size for inline use
  >
    <path d="M380.9 97.1C339 55.1 283.2 32 223.9 32c-122.4 0-222 99.6-222 222 0 39.1 10.2 77.3 29.6 111L0 480l117.7-30.9c32.4 17.7 68.9 27 106.1 27h.1c122.3 0 224.1-99.6 224.1-222 0-59.3-25.2-115-67.1-157zm-157 341.6c-33.2 0-65.7-8.9-94-25.7l-6.7-4-69.8 18.3L72 359.2l-4.4-7c-18.5-29.4-28.2-63.3-28.2-98.2 0-101.7 82.8-184.5 184.6-184.5 49.3 0 95.6 19.2 130.4 54.1 34.8 34.9 56.2 81.2 56.1 130.5 0 101.8-84.9 184.6-186.6 184.6zm101.2-138.2c-5.5-2.8-32.8-16.2-37.9-18-5.1-1.9-8.8-2.8-12.5 2.8-3.7 5.6-14.3 18-17.6 21.8-3.2 3.7-6.5 4.2-12 1.4-32.6-16.3-54-29.1-75.5-66-5.7-9.8 5.7-9.1 16.3-30.3 1.8-3.7.9-6.9-.5-9.7-1.4-2.8-12.5-30.1-17.1-41.2-4.5-10.8-9.1-9.3-12.5-9.5-3.2-.2-6.9-.2-10.6-.2-3.7 0-9.7 1.4-14.8 6.9-5.1 5.6-19.4 19-19.4 46.3 0 27.3 19.9 53.7 22.6 57.4 2.8 3.7 39.1 49.7 94.8 70.1 37.8 15.7 59.7 24.9 69.8 31.1 10.1 6.2 19.2 5.2 26.4 3.1 7.9-2.4 32.8-13.4 37.4-26.4 4.6-13 4.6-24.1 3.2-26.4-1.3-2.5-5-3.9-10.5-6.6z"/>
  </svg>
);

// TODO: Implement authentication check later
const isAuthenticated = false; // Placeholder

export default function ContatoPage() {
  const whatsappLink = `https://wa.me/5562982653996?text=${encodeURIComponent("Olá, Jaqueline! Gostaria de marcar uma conversa.")}`;

  return (
    <div className="container mx-auto px-4 py-12 md:py-20">
      <h1 className="mb-10 text-center text-4xl font-bold text-primary md:text-5xl">
        Entre em Contato
      </h1>
      <p className="mb-12 text-center text-lg text-muted-foreground max-w-2xl mx-auto">
        Estou aqui para ouvir você. Escolha a melhor forma de entrar em contato e vamos começar essa conversa.
      </p>

      <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
        {/* WhatsApp Contact Card */}
        <Card className="shadow-md">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-secondary-foreground">
              <WhatsAppIcon /> WhatsApp
            </CardTitle>
            <CardDescription>
              A forma mais rápida e direta de falar comigo. Clique no botão abaixo para iniciar uma conversa.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <p className="mb-4 flex items-center text-muted-foreground">
              <Phone className="mr-2 h-4 w-4" /> (62) 98265-3996
            </p>
            <Button asChild variant="accent" className="w-full">
              <a href={whatsappLink} target="_blank" rel="noopener noreferrer">
                <WhatsAppIcon /> <span className="ml-2">Falar no WhatsApp</span>
              </a>
            </Button>
          </CardContent>
        </Card>

        {/* Email Form Card (Conditional) */}
        <Card className="shadow-md">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-secondary-foreground">
              <Mail className="h-5 w-5" /> Formulário por Email
            </CardTitle>
            <CardDescription>
              Prefere enviar um email? Preencha o formulário abaixo (disponível para usuários logados).
            </CardDescription>
          </CardHeader>
          <CardContent>
            {isAuthenticated ? (
              <form className="space-y-4">
                 {/* TODO: Replace with actual form component using shadcn/ui Form */}
                 <div>
                    <label htmlFor="name" className="block text-sm font-medium text-muted-foreground mb-1">Nome</label>
                    <input type="text" id="name" name="name" className="w-full rounded-md border p-2 bg-input" placeholder="Seu nome" disabled/>
                 </div>
                 <div>
                    <label htmlFor="email" className="block text-sm font-medium text-muted-foreground mb-1">Email</label>
                    <input type="email" id="email" name="email" className="w-full rounded-md border p-2 bg-input" placeholder="seuemail@exemplo.com" disabled/>
                 </div>
                 <div>
                    <label htmlFor="message" className="block text-sm font-medium text-muted-foreground mb-1">Mensagem</label>
                    <textarea id="message" name="message" rows={4} className="w-full rounded-md border p-2 bg-input" placeholder="Sua mensagem..." disabled></textarea>
                 </div>
                 <Button type="submit" disabled className="w-full">Enviar Mensagem (Em Breve)</Button>
              </form>
            ) : (
              <div className="flex flex-col items-center justify-center h-full rounded-md border border-dashed p-8 text-center text-muted-foreground">
                 <p className="mb-4">O formulário de contato por email está disponível apenas para usuários autenticados.</p>
                 {/* TODO: Add Login Button */}
                 {/* <Button variant="outline" size="sm">Fazer Login</Button> */}
                 <p className="mt-4 text-sm">Por favor, utilize o WhatsApp para contato no momento.</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
